Prevent major/minor macro expansion in tests
Tests fail to compile with the following kind of error on FreeBSD 15.0
since commit 851e3ca1033b2382f1007f004664214e072a8b26:

/tmp/semver/test/test_advanced_ranges.cpp:33:13: error: no member named '__major' in 'semver::version<>'; did you mean 'major'?
   33 |     CHECK(v.major() == 1);
      |             ^
/usr/include/sys/types.h:331:18: note: expanded from macro 'major'
  331 | #define major(d)        __major(d)
      |                         ^
/tmp/semver/include/semver.hpp:351:39: note: 'major' declared here
  351 |     [[nodiscard]] SEMVER_CONSTEXPR I1 major() const noexcept { return major_; }
      |                                       ^
/tmp/semver/test/test_advanced_ranges.cpp:34:13: error: no member named '__minor' in 'semver::version<>'; did you mean 'minor'?
   34 |     CHECK(v.minor() == 2);
      |             ^
/usr/include/sys/types.h:337:18: note: expanded from macro 'minor'
  337 | #define minor(d)        __minor(d)
      |                         ^
/tmp/semver/include/semver.hpp:352:39: note: 'minor' declared here
  352 |     [[nodiscard]] SEMVER_CONSTEXPR I2 minor() const noexcept { return minor_; }
      |                                       ^
2 errors generated.

While semver.hpp undefs the major and minor macros if they are defined
by system headers on unix-like platforms (at least Linux, OpenBSD and
FreeBSD are known to define them), it doesn't prevent this kind of error
if such a system header is included after semver.hpp, which can happen
transitively.

The calling side has to accommodate for this on a case by case basis. To
fix the compilation of the tests, rearrange the semver.hpp include after
all other includes.